image: node

before_script:
  - npm install

cache:
  paths:
    - node_modules/

pages:
  script:
    - npm run generate
    - rm -rf public
    - mkdir public && cp -a .output/public/. public
  artifacts:
    paths:
      - public
  only:
    - main
